  - name: Check if Notepad ++ {{ notepad_version }} is installed
    win_stat:
      path: "C:/Program Files/Notepad++/notepad++.exe"
    register: notepad_installed

  - name: Install Notepad++ {{ notepad_version }}
    block:
    - name: Create Installs directory
      win_file:
        path: "{{ installations_dir }}"
        state: directory
    - name: Download installation file 
      win_get_url:   
        url: "{{ notepad_install_url }}"
        dest: "{{ installations_dir }}/npp.{{ notepad_version }}.Installer.x64.exe"
    - name: Install Application
      win_package:
        path: "{{ installations_dir }}/npp.{{ notepad_version }}.Installer.x64.exe"
        arguments: "/S"
    when: not notepad_installed.stat.exists