- name: Set exclusion for {{ item }}
  win_dsc:
    resource_name: 'RegistryPolicyFile'
    Key: 'Software\Policies\Microsoft\Windows Defender\Exclusions\Paths'
    TargetType: ComputerConfiguration
    ValueType: Dword
    ValueName: "{{ item }}"
    ValueData: 0